### ISSUE TITLE
请问你用的是哪个版本的tensorflow呢，运行报错AttributeError: module 'tensorflow' has no attribute 'placeholder'

### ISSUE THREAD

**Issue by lynn0909** [Udolf15/GEAR-Predictor#1]
你好，我运行报错AttributeError: module 'tensorflow' has no attribute 'placeholder'，想请问一下你运行的tensorflow版本，十分感谢！

**Comment by Moon0shang** [comment]
> 你好，我运行报错AttributeError: module 'tensorflow' has no attribute 'placeholder'，想请问一下你运行的tensorflow版本，十分感谢！

目测是1点几的版本，2.0以后的版本和pytorch一样变得更pythonic了

**Comment by Udolf15** [comment]
tensorflow 1.13.1
keras 2.2.4
