### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by Lily19970207** [Udolf15/GEAR-Predictor#3]
Hello.I am interested in this project and I want to achieve an application like it.I know you built a neural network for this project,but I do not know which method you used.I want to know more details.Can you describe your project detailedly,such as algorithm,framework and so on.Thanks.

**Comment by hashmi-masif** [comment]
Hi @Lily19970207,

I apologize for replying late. I was busy at that time and then forgot about this. If you are still interested you can ping me again. I will let you know the details.
